Add new element in Matrix

diff --git a/JenkinsfileMatrix b/JenkinsfileMatrix
--- a/JenkinsfileMatrix
+++ b/JenkinsfileMatrix
@@ -72,60 +72,60 @@ pipeline {
                     }
                 }
                 stage('InstallTest'){
-                            steps {
-                                echo 'InstallCMSSW Test step..'
-                                sh '''
-                                pwd
-                                cd test_dir
-                                source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-                                source ../HGCTPGValidation/scripts/getScramArch.sh $REF_RELEASE
-                                if [ -z "$CHANGE_FORK" ]
-                                then
-                                    export REMOTE=$BASE_REMOTE
-                                else
-                                    export REMOTE=$CHANGE_FORK
-                                fi
-                                echo 'REMOTE= ', $REMOTE
-                                ../HGCTPGValidation/scripts/installCMSSW.sh $SCRAM_ARCH $REF_RELEASE $REMOTE $CHANGE_BRANCH $CHANGE_TARGET ${LABEL_TEST}
-                                '''
-                            }
+					steps {
+						echo 'InstallCMSSW Test step..'
+						sh '''
+						pwd
+						cd test_dir
+						source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+						source ../HGCTPGValidation/scripts/getScramArch.sh $REF_RELEASE
+						if [ -z "$CHANGE_FORK" ]
+						then
+							export REMOTE=$BASE_REMOTE
+						else
+							export REMOTE=$CHANGE_FORK
+						fi
+						echo 'REMOTE= ', $REMOTE
+						../HGCTPGValidation/scripts/installCMSSW.sh $SCRAM_ARCH $REF_RELEASE $REMOTE $CHANGE_BRANCH $CHANGE_TARGET ${LABEL_TEST}
+						'''
+					}
                 }
                 stage('QualityChecks'){
-                            steps{
-                                sh '''
-                                source /cvmfs/cms.cern.ch/cmsset_default.sh
-                                source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-                                cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${LABEL_TEST}/src
-                                scram build code-checks
-                                scram build code-format
-                                GIT_STATUS=`git status --porcelain`
-                                if [ ! -z "$GIT_STATUS" ]; then
-                                    echo "Code-checks or code-format failed."
-                                    exit 1;
-                                fi
-                                '''
-                            }
+					steps{
+						sh '''
+						source /cvmfs/cms.cern.ch/cmsset_default.sh
+						source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+						cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${LABEL_TEST}/src
+						scram build code-checks
+						scram build code-format
+						GIT_STATUS=`git status --porcelain`
+						if [ ! -z "$GIT_STATUS" ]; then
+							echo "Code-checks or code-format failed."
+							exit 1;
+						fi
+						'''
+					}
                 }
                 stage('InstallRef'){
-                            steps {
-                                echo 'InstallCMSSW Ref step..'
-                                sh '''
-                                pwd
-                                cd test_dir
-                                source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-                                source ../HGCTPGValidation/scripts/getScramArch.sh $REF_RELEASE
-                                ../HGCTPGValidation/scripts/installCMSSW.sh $SCRAM_ARCH $REF_RELEASE $BASE_REMOTE $CHANGE_TARGET $CHANGE_TARGET ${LABEL_REF}
-                                '''
-                            }
+                    steps {
+                        echo 'InstallCMSSW Ref step..'
+                        sh '''
+                        pwd
+                        cd test_dir
+                        source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                        source ../HGCTPGValidation/scripts/getScramArch.sh $REF_RELEASE
+                        ../HGCTPGValidation/scripts/installCMSSW.sh $SCRAM_ARCH $REF_RELEASE $BASE_REMOTE $CHANGE_TARGET $CHANGE_TARGET ${LABEL_REF}
+                        '''
+                    }
                 }  
             }
         }
-        stage('Build'){
+        stage('Produce'){
             matrix {
                 axes {
                     axis {
                         name 'TEST'
-                        values 'bcstc'
+                        values 'bcstc', 'default'
                     }
                     axis {
                         name 'REF'
@@ -133,76 +133,67 @@ pipeline {
                     }
                 }
                 stages{
-                    stage('BuildCMSSWTest'){
-                    stages{
-                        stage('Produce'){
-                            steps {
-                                sh '''
-                                pwd
-                                source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-                                cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${LABEL_TEST}/src
-                                module use /opt/exp_soft/vo.llr.in2p3.fr/modulefiles_el7/
-                                module purge
-                                module load python/3.9.9
-                                python --version
-                                echo ' CONFIG_SUBSET = ' ${CONFIG_SUBSET}
-                                echo 'LABEL_TEST = ' ${LABEL_TEST}
-                                echo 'Test Produce Do Build for ${TEST} - ${REF}'
-                                python ../../../HGCTPGValidation/scripts/produceData_from_configuration_matrix.py --subsetconfig ${CONFIG_SUBSET} --label ${LABEL_TEST} --config ${TEST}
-                                ls -lrt
-                                '''     
-                            }
+                    stage('ProduceTest'){         
+                        steps {
+                            sh '''
+                            pwd
+                            source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                            cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${LABEL_TEST}/src
+                            module use /opt/exp_soft/vo.llr.in2p3.fr/modulefiles_el7/
+                            module purge
+                            module load python/3.9.9
+                            python --version
+                            echo ' CONFIG_SUBSET = ' ${CONFIG_SUBSET}
+                            echo 'LABEL_TEST = ' ${LABEL_TEST}
+                            echo 'Test Produce Do Build for ${TEST} - ${REF}'
+                            python ../../../HGCTPGValidation/scripts/produceData_from_configuration_matrix.py --subsetconfig ${CONFIG_SUBSET} --label ${LABEL_TEST} --config ${TEST}
+                            ls -lrt
+                            '''     
+                        }             
+                    }          
+                    stage('ProduceRef'){
+                        steps {
+                            sh '''
+                            pwd
+                            source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                            cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${LABEL_REF}/src
+                            module use /opt/exp_soft/vo.llr.in2p3.fr/modulefiles_el7/
+                            module purge
+                            module load python/3.9.9
+                            python --version
+                            echo ' CONFIG_SUBSET = ' ${CONFIG_SUBSET}
+                            echo 'Ref Produce Do Build for ${TEST} - ${REF}'
+                            python ../../../HGCTPGValidation/scripts/produceData_from_configuration_matrix.py --subsetconfig ${CONFIG_SUBSET} --label ${LABEL_REF} --config ${REF} 
+                            ls -lrt
+                            '''            
+                        }
+                    }
+                    stage('Display') {
+                        steps {
+                            sh '''
+                            cd test_dir
+                            source ../HGCTPGValidation/env_install.sh
+                            echo $PWD
+                            source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                            ../HGCTPGValidation/scripts/displayHistos.sh ./${REF_RELEASE}_HGCalTPGValidation_${LABEL_REF}/src ./${REF_RELEASE}_HGCalTPGValidation_${LABEL_TEST}/src ./GIFS
+                            echo 'CHANGE_ID= ', $CHANGE_ID
+                            echo '$CHANGE_TITLE= ', $CHANGE_TITLE
+                            if [ -d /data/jenkins/workspace/${DATA_DIR}/PR$CHANGE_ID ] 
+                            then
+                                echo "Directory " PR$CHANGE_ID " exists." 
+                                rm -rf /data/jenkins/workspace/${DATA_DIR}/PR$CHANGE_ID
+                            fi
+                            echo 'Display Do Build for ${TEST} - ${REF}'
+                            export data_dir=/data/jenkins/workspace/${DATA_DIR}/
+                            mkdir $data_dir/PR$CHANGE_ID
+                            mkdir $data_dir/PR$CHANGE_ID/"PR$CHANGE_ID"config1
+                            cp -rf GIFS/. $data_dir/PR$CHANGE_ID/"PR$CHANGE_ID"config1
+                            python ../HGCTPGValidation/scripts/writeToFile.py --dirname $data_dir/PR$CHANGE_ID --prnumber $CHANGE_ID --prtitle "$CHANGE_TITLE (from $CHANGE_AUTHOR, $CHANGE_URL)"
+                            '''            
                         }
                     }
                 }
-                stage('BuildCMSSWRef'){
-                    stages{
-         
-                        stage('Produce'){
-                            steps {
-                                sh '''
-                                pwd
-                                source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-                                cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${LABEL_REF}/src
-                                module use /opt/exp_soft/vo.llr.in2p3.fr/modulefiles_el7/
-                                module purge
-                                module load python/3.9.9
-                                python --version
-                                echo ' CONFIG_SUBSET = ' ${CONFIG_SUBSET}
-                                echo 'Ref Produce Do Build for ${TEST} - ${REF}'
-                                python ../../../HGCTPGValidation/scripts/produceData_from_configuration_matrix.py --subsetconfig ${CONFIG_SUBSET} --label ${LABEL_REF} --config ${REF} 
-                                ls -lrt
-                                '''            
-                            }
-                        }
-                    }
-                }
-                stage('Display') {
-                    steps {
-                        sh '''
-                        cd test_dir
-                        source ../HGCTPGValidation/env_install.sh
-                        echo $PWD
-                        source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-                        ../HGCTPGValidation/scripts/displayHistos.sh ./${REF_RELEASE}_HGCalTPGValidation_${LABEL_REF}/src ./${REF_RELEASE}_HGCalTPGValidation_${LABEL_TEST}/src ./GIFS
-                        echo 'CHANGE_ID= ', $CHANGE_ID
-                        echo '$CHANGE_TITLE= ', $CHANGE_TITLE
-                        if [ -d /data/jenkins/workspace/${DATA_DIR}/PR$CHANGE_ID ] 
-                        then
-                            echo "Directory " PR$CHANGE_ID " exists." 
-                            rm -rf /data/jenkins/workspace/${DATA_DIR}/PR$CHANGE_ID
-                        fi
-                        echo 'Display Do Build for ${TEST} - ${REF}'
-                        export data_dir=/data/jenkins/workspace/${DATA_DIR}/
-                        mkdir $data_dir/PR$CHANGE_ID
-                        mkdir $data_dir/PR$CHANGE_ID/"PR$CHANGE_ID"config1
-                        cp -rf GIFS/. $data_dir/PR$CHANGE_ID/"PR$CHANGE_ID"config1
-                        python ../HGCTPGValidation/scripts/writeToFile.py --dirname $data_dir/PR$CHANGE_ID --prnumber $CHANGE_ID --prtitle "$CHANGE_TITLE (from $CHANGE_AUTHOR, $CHANGE_URL)"
-                        '''            
-                    }
-                } 
             }
-        }
         }
     }
     post {
