Adapt to multoconfig
Create a specific directory for each config histos

diff --git a/JenkinsfileMatrixGlobal b/JenkinsfileMatrixGlobal
--- a/JenkinsfileMatrixGlobal
+++ b/JenkinsfileMatrixGlobal
@@ -1,3 +1,4 @@
+
 pipeline {
     agent {
         label 'llrgrhgtrig.in2p3.fr'
@@ -87,118 +88,118 @@ pipeline {
                 }
                 stages{
                     stage('BuildCMSSWTest'){
-						stages{
-							stage('Install'){
-								steps {
-									echo 'InstallCMSSW Test step..'
-									sh '''
-									pwd
-									cd test_dir
-									source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-									source ../HGCTPGValidation/scripts/getScramArch.sh $REF_RELEASE
-									if [ -z "$CHANGE_FORK" ]
-									then
-										export REMOTE=$BASE_REMOTE
-									else
-										export REMOTE=$CHANGE_FORK
-									fi
-									echo 'REMOTE= ', $REMOTE
-									../HGCTPGValidation/scripts/installCMSSW_matrix.sh $SCRAM_ARCH $REF_RELEASE $REMOTE $CHANGE_BRANCH $CHANGE_TARGET ${LABEL_TEST} ${TEST}
-									'''
-								}
-							}
-							stage('QualityChecks'){
-								steps{
-									sh '''
-									source /cvmfs/cms.cern.ch/cmsset_default.sh
-									source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-									cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${TEST}_${LABEL_TEST}/src
-									scram build code-checks
-									scram build code-format
-									GIT_STATUS=`git status --porcelain`
-									if [ ! -z "$GIT_STATUS" ]; then
-										echo "Code-checks or code-format failed."
-										exit 1;
-									fi
-									'''
-								}
-							}
-							stage('Produce'){
-								steps {
-									sh '''
-									pwd
-									source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-									cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${TEST}_${LABEL_TEST}/src
-									module use /opt/exp_soft/vo.llr.in2p3.fr/modulefiles_el7/
-									module purge
-									module load python/3.9.9
-									python --version
-									echo ' CONFIG_SUBSET = ' ${CONFIG_SUBSET}
-									echo 'LABEL_TEST = ' ${LABEL_TEST}
-									echo 'Test Produce Do Build for ${TEST} - ${REF}'
-									python ../../../HGCTPGValidation/scripts/produceData_from_configuration.py --subsetconfig ${CONFIG_SUBSET} --label ${LABEL_TEST} --config ${TEST}
-									'''     
-								}
-							}
-						}
-					}
-					stage('BuildCMSSWRef'){
-						stages{
-							stage('Install'){
-								steps {
-									echo 'InstallCMSSW Ref step..'
-									sh '''
-									pwd
-									cd test_dir
-									source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-									source ../HGCTPGValidation/scripts/getScramArch.sh $REF_RELEASE
-									../HGCTPGValidation/scripts/installCMSSW_matrix.sh $SCRAM_ARCH $REF_RELEASE $BASE_REMOTE $CHANGE_TARGET $CHANGE_TARGET ${LABEL_REF} ${REF}
-									'''
-								}
-							}           
-							stage('Produce'){
-								steps {
-									sh '''
-									pwd
-									source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-									cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${REF}_${LABEL_REF}/src
-									module use /opt/exp_soft/vo.llr.in2p3.fr/modulefiles_el7/
-									module purge
-									module load python/3.9.9
-									python --version
-									echo ' CONFIG_SUBSET = ' ${CONFIG_SUBSET}
-									echo 'Ref Produce Do Build for ${TEST} - ${REF}'
-									python ../../../HGCTPGValidation/scripts/produceData_from_configuration.py --subsetconfig ${CONFIG_SUBSET} --label ${LABEL_REF} --config ${REF}
-									'''            
-								}
-							}
-						}
-					}
-					stage('Display') {
-						steps {
-							sh '''
-							cd test_dir
-							source ../HGCTPGValidation/env_install.sh
-							echo $PWD
-							source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
-							../HGCTPGValidation/scripts/displayHistos.sh ./${REF_RELEASE}_HGCalTPGValidation_${REF}_${LABEL_REF}/src ./${REF_RELEASE}_HGCalTPGValidation_${TEST}_${LABEL_TEST}/src ./GIFS
-							echo 'CHANGE_ID= ', $CHANGE_ID
-							echo '$CHANGE_TITLE= ', $CHANGE_TITLE
-							if [ -d /data/jenkins/workspace/${DATA_DIR}/PR$CHANGE_ID ] 
-							then
-								echo "Directory " PR$CHANGE_ID " exists." 
-								rm -rf /data/jenkins/workspace/${DATA_DIR}/PR$CHANGE_ID
-							fi
-							echo 'Display Do Build for ${TEST} - ${REF}'
-							export data_dir=/data/jenkins/workspace/${DATA_DIR}/
-							mkdir $data_dir/PR$CHANGE_ID
-							mkdir $data_dir/PR$CHANGE_ID/"PR$CHANGE_ID"config1
-							cp -rf GIFS/. $data_dir/PR$CHANGE_ID/"PR$CHANGE_ID"config1
-							python ../HGCTPGValidation/scripts/writeToFile.py --dirname $data_dir/PR$CHANGE_ID --prnumber $CHANGE_ID --prtitle "$CHANGE_TITLE (from $CHANGE_AUTHOR, $CHANGE_URL)"
-							'''            
-						}
-					}
-				}
+                        stages{
+                            stage('Install'){
+                                steps {
+                                    echo 'InstallCMSSW Test step..'
+                                    sh '''
+                                    pwd
+                                    cd test_dir
+                                    source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                                    source ../HGCTPGValidation/scripts/getScramArch.sh $REF_RELEASE
+                                    if [ -z "$CHANGE_FORK" ]
+                                    then
+                                        export REMOTE=$BASE_REMOTE
+                                    else
+                                        export REMOTE=$CHANGE_FORK
+                                    fi
+                                    echo 'REMOTE= ', $REMOTE
+                                    ../HGCTPGValidation/scripts/installCMSSW_matrix.sh $SCRAM_ARCH $REF_RELEASE $REMOTE $CHANGE_BRANCH $CHANGE_TARGET ${LABEL_TEST} ${TEST}
+                                    '''
+                                }
+                            }
+                            stage('QualityChecks'){
+                                steps{
+                                    sh '''
+                                    source /cvmfs/cms.cern.ch/cmsset_default.sh
+                                    source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                                    cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${TEST}_${LABEL_TEST}/src
+                                    scram build code-checks
+                                    scram build code-format
+                                    GIT_STATUS=`git status --porcelain`
+                                    if [ ! -z "$GIT_STATUS" ]; then
+                                        echo "Code-checks or code-format failed."
+                                        exit 1;
+                                    fi
+                                    '''
+                                }
+                            }
+                            stage('Produce'){
+                                steps {
+                                    sh '''
+                                    pwd
+                                    source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                                    cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${TEST}_${LABEL_TEST}/src
+                                    module use /opt/exp_soft/vo.llr.in2p3.fr/modulefiles_el7/
+                                    module purge
+                                    module load python/3.9.9
+                                    python --version
+                                    echo ' CONFIG_SUBSET = ' ${CONFIG_SUBSET}
+                                    echo 'LABEL_TEST = ' ${LABEL_TEST}
+                                    echo 'Test Produce Do Build for ${TEST} - ${REF}'
+                                    python ../../../HGCTPGValidation/scripts/produceData_from_configuration.py --subsetconfig ${CONFIG_SUBSET} --label ${LABEL_TEST} --config ${TEST}
+                                    '''     
+                                }
+                            }
+                        }
+                    }
+                    stage('BuildCMSSWRef'){
+                        stages{
+                            stage('Install'){
+                                steps {
+                                    echo 'InstallCMSSW Ref step..'
+                                    sh '''
+                                    pwd
+                                    cd test_dir
+                                    source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                                    source ../HGCTPGValidation/scripts/getScramArch.sh $REF_RELEASE
+                                    ../HGCTPGValidation/scripts/installCMSSW_matrix.sh $SCRAM_ARCH $REF_RELEASE $BASE_REMOTE $CHANGE_TARGET $CHANGE_TARGET ${LABEL_REF} ${REF}
+                                    '''
+                                }
+                            }           
+                            stage('Produce'){
+                                steps {
+                                    sh '''
+                                    pwd
+                                    source ./HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                                    cd test_dir/${REF_RELEASE}_HGCalTPGValidation_${REF}_${LABEL_REF}/src
+                                    module use /opt/exp_soft/vo.llr.in2p3.fr/modulefiles_el7/
+                                    module purge
+                                    module load python/3.9.9
+                                    python --version
+                                    echo ' CONFIG_SUBSET = ' ${CONFIG_SUBSET}
+                                    echo 'Ref Produce Do Build for ${TEST} - ${REF}'
+                                    python ../../../HGCTPGValidation/scripts/produceData_from_configuration.py --subsetconfig ${CONFIG_SUBSET} --label ${LABEL_REF} --config ${REF}
+                                    '''            
+                                }
+                            }
+                        }
+                    }
+                    stage('Display') {
+                        steps {
+                            sh '''
+                            cd test_dir
+                            source ../HGCTPGValidation/env_install.sh
+                            echo $PWD
+                            source ../HGCTPGValidation/scripts/extractReleaseName.sh $CHANGE_TARGET
+                            ../HGCTPGValidation/scripts/displayHistos.sh ./${REF_RELEASE}_HGCalTPGValidation_${REF}_${LABEL_REF}/src ./${REF_RELEASE}_HGCalTPGValidation_${TEST}_${LABEL_TEST}/src ./GIFS
+                            echo 'CHANGE_ID= ', $CHANGE_ID
+                            echo '$CHANGE_TITLE= ', $CHANGE_TITLE
+                            if [ -d /data/jenkins/workspace/${DATA_DIR}/PR$CHANGE_ID ] 
+                            then
+                                echo "Directory " PR$CHANGE_ID " exists." 
+                                rm -rf /data/jenkins/workspace/${DATA_DIR}/PR$CHANGE_ID
+                            fi
+                            echo 'Display Do Build for ${TEST} - ${REF}'
+                            export data_dir=/data/jenkins/workspace/${DATA_DIR}/
+                            mkdir $data_dir/PR$CHANGE_ID
+                            mkdir $data_dir/PR$CHANGE_ID/"PR$CHANGE_ID_"${TEST}_${REF}
+                            cp -rf GIFS/. $data_dir/PR$CHANGE_ID/"PR$CHANGE_ID_"${TEST}_${REF}
+                            python ../HGCTPGValidation/scripts/writeToFile.py --dirname $data_dir/PR$CHANGE_ID --prnumber $CHANGE_ID --prtitle "$CHANGE_TITLE (from $CHANGE_AUTHOR, $CHANGE_URL)"
+                            '''            
+                        }
+                    }
+                }
             }
         }
     }
