Added all stages for Test release

diff --git a/JenkinsfileTest b/JenkinsfileTest
--- a/JenkinsfileTest
+++ b/JenkinsfileTest
@@ -62,9 +62,10 @@ pipeline{
         do
            counter=$(( $counter + 1 ))
            echo $counter 
+           echo ' Subset = ' SUBSET_TEST_$counter
            echo /data/jenkins/workspace/${DATA_DIR}/"PR${CHANGE_ID}"config$counter
            if [ -d "/data/jenkins/workspace/${DATA_DIR}/"PR${CHANGE_ID}"config$counter" ] 
-             then
+           then
              rm -rf /data/jenkins/workspace/${DATA_DIR}/"PR${CHANGE_ID}"config$counter
            fi
         done
@@ -73,17 +74,115 @@ pipeline{
     }
     stage('BuildCMSSWTest'){
       stages{
-          stage('Install'){
-              steps {
+        stage('Install'){
+          steps {
                   echo 'InstallCMSSW Test step..'
                    sh '''
-                   pwd    
+                   pwd
+                   SCRAM_ARCH='slc7_amd64_gcc10'
+                   export SCRAM_ARCH
+                   REF_RELEASE='CMSSW_12_1_0_pre3'
+                   export REF_RELEASE
+                   REMOTE='ebecheva'
+                   export REMOTE
+                   LABEL_TEST="test"
+                   export LABEL_TEST
+                   export CHANGE_BRANCH="fix-dev-CMSSW_12_1_0_pre3"
+                   export CHANGE_TARGET="main-dev-CMSSW_12_1_0_pre3"
+                   counter=1
+                   echo 'SUBSET_TEST_$counter= ' SUBSET_TEST_$counter
+                   while [ $counter -le $NB_CONFIGS ]
+                   do
+                     echo $counter
+                     subset=SUBSET_TEST_$counter
+                     sub=${!subset}
+                     if [ !${REF_RELEASE}_HGCalTPGValidation_${sub}_${LABEL_TEST} ]
+                     then
+                       ./scripts/installCMSSW_multiconfig.sh $SCRAM_ARCH $REF_RELEASE $REMOTE $CHANGE_BRANCH $CHANGE_TARGET ${LABEL_TEST} $sub
+                       counter=$(( $counter + 1 ))
+                     else
+                       echo 'The directory ${REF_RELEASE}_HGCalTPGValidation_${sub}_${LABEL_TEST} already exists.'
+                       exit
+                     fi
+                    done
                    '''     
-              }
-          
           }
-      }
-      
+        }
+        stage('QualityChecks'){
+          steps{
+            sh '''
+                SCRAM_ARCH='slc7_amd64_gcc10'
+                export SCRAM_ARCH
+                REF_RELEASE='CMSSW_12_1_0_pre3'
+                export REF_RELEASE
+                REMOTE='ebecheva'
+                export REMOTE
+                LABEL_TEST="test"
+                export LABEL_TEST
+                export CHANGE_BRANCH="fix-dev-CMSSW_12_1_0_pre3"
+                export CHANGE_TARGET="main-dev-CMSSW_12_1_0_pre3"
+                source /cvmfs/cms.cern.ch/cmsset_default.sh
+                counter=1
+                echo 'SUBSET_TEST_$counter= ' SUBSET_TEST_$counter
+                while [ $counter -le $NB_CONFIGS ]
+                do
+                    echo $counter
+                    subset=SUBSET_TEST_$counter
+                    sub=${!subset}
+                    echo "${REF_RELEASE}_HGCalTPGValidation_${sub}_${LABEL_TEST}/src"
+                    cd ${REF_RELEASE}_HGCalTPGValidation_${sub}_${LABEL_TEST}/src
+                    scram build code-checks
+                    scram build code-format
+                    GIT_STATUS=`git status --porcelain`
+                    if [ ! -z "$GIT_STATUS" ]; then
+                        echo "Code-checks or code-format failed."
+                        exit 1;
+                    fi
+                    counter=$(( $counter + 1 ))
+                    cd ../..
+                done
+            '''
+          }
+        }
+        stage('Produce'){
+            steps {
+                sh '''
+                pwd
+                SCRAM_ARCH='slc7_amd64_gcc10'
+                export SCRAM_ARCH
+                REF_RELEASE='CMSSW_12_1_0_pre3'
+                export REF_RELEASE
+                REMOTE='ebecheva'
+                export REMOTE
+                LABEL_TEST="test"
+                export LABEL_TEST
+                export CHANGE_BRANCH="fix-dev-CMSSW_12_1_0_pre3"
+                export CHANGE_TARGET="main-dev-CMSSW_12_1_0_pre3"
+                source /cvmfs/cms.cern.ch/cmsset_default.sh
+                counter=1
+                while [ $counter -le $NB_CONFIGS ]
+                do
+                    echo $counter
+                    subset=SUBSET_TEST_$counter
+                    sub=${!subset}
+                    if [ !${REF_RELEASE}_HGCalTPGValidation_${sub}_${LABEL_TEST} ]
+                    then
+                        cd ${REF_RELEASE}_HGCalTPGValidation_${sub}_${LABEL_TEST}/src
+                        module use /opt/exp_soft/vo.llr.in2p3.fr/modulefiles_el7/
+                        module purge
+                        module load python/3.9.9
+                        python --version
+                        echo 'LABEL_TEST = ' ${LABEL_TEST}
+                        python ../../scripts/produceData_from_configuration.py --subsetconfig ${sub} --label ${LABEL_TEST}
+                    else
+                        echo 'The data for this configuration have been already produced'
+                        exit
+                    fi
+                done
+                '''     
+            }
+        }  
     }
+  }
   }
 }
